#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

REMOVE="rm -rf .next/ .turbo/ dist/ public/sw.js public/sw.js.map \
              public/workbox-*.js public/workbox-*.js.map yarn-error.log \
              .swc/ .eslintcache .prettiercache .contentlayercache \
              .contentlayercache.lock .contentlayer .stylelintcache \
              .stylelintignorecache .stylelintignorecache.lock .stylelintcache"

# remove files from previous builds
eval $REMOVE

# lint and build
pnpm lint

# lint and fix
pnpm lint:fix

# format code
pnpm format

# build and test for truthy
pnpm build
# test for last command executed
if [ $? -eq 0 ]; then
  # remove build files
  eval $REMOVE

  # stage files for commit
  git add .

  echo "Staged changes and Build Successful 😆!"
  exit 0

  else
    echo "Oops! Build failed 😢."
    exit 130
fi
